### ISSUE TITLE
BigEarthNet evlaution -- PR, and multi-label, predictions

### ISSUE THREAD

**Issue by TsungChinHanKen** [Berkeley-Data/hpt#75]

**Comment by TsungChinHanKen** [comment]
1. print prediction and/or images (Surya to merge the changes from Ernesto and create PR) 
2. evaluate BE dataset on multi-label (Taeil: once 1 is confirmed) 
3. training curve and/ or confusion matrix?

**Comment by suryatechie** [comment]
The first one in the above list is done.  Code is checked in.
![image](https://user-images.githubusercontent.com/15736461/114260840-16af7200-998c-11eb-81b3-a9810415297b.png)

**Comment by suryatechie** [comment]
By default, it's disabled. To enable it, add **--output_pred** while running the main_train.py script. It's generating ~50MB of data for sen12ms. For bigearthnet, it will be very big as the test dataset is around 120k samples.

**Comment by taeil** [comment]
thanks
